-- ==============================================================================
-- SWEETY COLOUR DECORA — SUPABASE POSTGRESQL PRODUCTION SCHEMA
-- Run this script in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 1. USERS & ROLES
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'SITE_SUPERVISOR' CHECK (role IN ('OWNER', 'ADMIN', 'PROJECT_MANAGER', 'SITE_SUPERVISOR', 'ACCOUNTANT')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PROJECTS LEDGER
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  client_name TEXT NOT NULL,
  client_email TEXT,
  client_phone TEXT,
  location TEXT,
  city TEXT DEFAULT 'Bengaluru',
  project_type TEXT DEFAULT 'Interior',
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  expected_completion DATE,
  contract_value NUMERIC(14, 2) NOT NULL DEFAULT 0,
  estimated_budget NUMERIC(14, 2) NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'COMPLETED', 'ON_HOLD', 'DELAYED')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. WORKFORCE ROSTER
CREATE TABLE IF NOT EXISTS public.workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_name TEXT NOT NULL,
  phone TEXT,
  trade TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('MASTER_CRAFTSMAN', 'MASON', 'CARPENTER', 'PAINTER', 'POP_SPECIALIST', 'ELECTRICIAN', 'HELPER')),
  daily_wage_rate NUMERIC(10, 2) NOT NULL DEFAULT 950.00,
  overtime_hourly_rate NUMERIC(10, 2) NOT NULL DEFAULT 150.00,
  assigned_project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. DAILY ATTENDANCE & FIELD TELEMETRY
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES public.workers(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'PRESENT' CHECK (status IN ('PRESENT', 'ABSENT', 'HALF_DAY', 'OVERTIME')),
  regular_hours NUMERIC(4, 2) DEFAULT 8.0,
  overtime_hours NUMERIC(4, 2) DEFAULT 0.0,
  wage_earned NUMERIC(10, 2) NOT NULL DEFAULT 0,
  work_completed TEXT,
  logged_by_supervisor TEXT DEFAULT 'Ramesh Patel',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (worker_id, date, project_id)
);

-- 5. WORK ASSIGNMENTS & PROGRESS
CREATE TABLE IF NOT EXISTS public.work_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  trade TEXT NOT NULL,
  assigned_worker_id BIGINT REFERENCES public.workers(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED')),
  progress_pct INTEGER DEFAULT 0 CHECK (progress_pct BETWEEN 0 AND 100),
  deadline DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. MATERIALS PROCUREMENT CATALOG & INVOICES
CREATE TABLE IF NOT EXISTS public.material_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  material_name TEXT NOT NULL,
  category TEXT NOT NULL,
  quantity NUMERIC(10, 2) NOT NULL,
  unit TEXT NOT NULL DEFAULT 'sq.ft',
  unit_price NUMERIC(10, 2) NOT NULL,
  total_cost NUMERIC(14, 2) NOT NULL,
  supplier TEXT,
  invoice_number TEXT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'DELIVERED',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. PROJECT EXPENSES & ACCOUNTS
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  amount NUMERIC(14, 2) NOT NULL,
  description TEXT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. DAILY SITE REPORTS & AUDITS
CREATE TABLE IF NOT EXISTS public.daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  supervisor_name TEXT NOT NULL DEFAULT 'Ramesh Patel',
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  workers_present_count INTEGER DEFAULT 0,
  work_completed TEXT NOT NULL,
  materials_used TEXT,
  problems TEXT,
  safety_issues TEXT,
  ai_observations TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. WEBSITE LEADS & CONSULTATIONS
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  city TEXT DEFAULT 'Bengaluru',
  project_type TEXT DEFAULT 'Interior',
  preferred_time TEXT,
  notes TEXT,
  ai_design_data JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Allow public read/write for demo & API service role access
CREATE POLICY "Public Read Projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public Insert Projects" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Projects" ON public.projects FOR UPDATE USING (true);

CREATE POLICY "Public Read Workers" ON public.workers FOR SELECT USING (true);
CREATE POLICY "Public Write Workers" ON public.workers FOR ALL USING (true);

CREATE POLICY "Public Read Attendance" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Public Write Attendance" ON public.attendance FOR ALL USING (true);

CREATE POLICY "Public Read Work Items" ON public.work_items FOR SELECT USING (true);
CREATE POLICY "Public Write Work Items" ON public.work_items FOR ALL USING (true);

CREATE POLICY "Public Read Materials" ON public.material_purchases FOR SELECT USING (true);
CREATE POLICY "Public Write Materials" ON public.material_purchases FOR ALL USING (true);

CREATE POLICY "Public Read Expenses" ON public.expenses FOR SELECT USING (true);
CREATE POLICY "Public Write Expenses" ON public.expenses FOR ALL USING (true);

CREATE POLICY "Public Read Daily Reports" ON public.daily_reports FOR SELECT USING (true);
CREATE POLICY "Public Write Daily Reports" ON public.daily_reports FOR ALL USING (true);

CREATE POLICY "Public Insert Leads" ON public.leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Leads" ON public.leads FOR SELECT USING (true);

-- ==============================================================================
-- INITIAL SEED DATA
-- ==============================================================================
INSERT INTO public.projects (name, client_name, client_email, client_phone, location, city, project_type, start_date, expected_completion, contract_value, estimated_budget, status)
VALUES
  ('Emerald Heights Penthouse Finish', 'Vikramaditya Singhania', 'singhania@emerald.com', '+91 98201 11223', 'Bandra West, Hill Road', 'Mumbai', 'Interior', '2026-08-01', '2026-10-15', 6800000, 5200000, 'ACTIVE'),
  ('Prestige Silver Oak Master Living Room', 'Ananya Deshmukh', 'ananya.d@prestige.in', '+91 98450 44556', 'Whitefield', 'Bengaluru', 'Interior', '2026-08-15', '2026-10-30', 2850000, 2200000, 'ACTIVE'),
  ('Surat Diamond Bourse Suite Fitout', 'Pravinbhai Kothari', 'kothari@sdb.co', '+91 98251 77889', 'Khajod Dream City', 'Ahmedabad', 'Commercial', '2026-07-10', '2026-11-20', 12500000, 9500000, 'ACTIVE');

INSERT INTO public.workers (worker_name, phone, trade, role, daily_wage_rate, overtime_hourly_rate, assigned_project_id)
VALUES
  ('Ramesh Patel', '+91 98250 11001', 'Master Finisher', 'MASTER_CRAFTSMAN', 1500, 250, 1),
  ('Suresh Kumar', '+91 98250 11002', 'Italian Stucco', 'PAINTER', 1100, 180, 1),
  ('Dinesh Sharma', '+91 98250 11003', 'POP & False Ceiling', 'POP_SPECIALIST', 1050, 160, 2),
  ('Mohan Lal', '+91 98250 11004', 'Flooring & Marble', 'MASON', 1200, 200, 1),
  ('Arun Verma', '+91 98250 11005', 'Electrical & Coves', 'ELECTRICIAN', 1150, 190, 2);
